version: "3"

services:
  api:
    build: url-shortner_app_1
    ports:
      - "3000:3000"
    depends_on:
      - url-shortner_db_1
  db:
    build: url-shortner_db_1
    ports:
      - "6379:6379"
    volumes:
      - .data:/data